### ISSUE TITLE
unix flag conventions

### ISSUE THREAD

**Issue by netizen-a** [philip-w-howard/stackl#19]
I noticed the program flags for stackl uses a single `-` instead of two dashes. 

This may be confusing to users without explicit documentation. Most unix programs would have a single `-` for letter flags, and `--` for entire words. Please consider this change for intuitive use of the program, so that users such as myself can easily access the help menu using common flags like `-h` and `--help`.

**Comment by philip-w-howard** [comment]
The newly released V1.0.1-6 should resolve this issue.
