### ISSUE TITLE
BUG: Divide by zero

### ISSUE THREAD

**Issue by netizen-a** [philip-w-howard/stackl#26]
## Summary of problem
Division by zero does not machine check, but instead crashes stackl itself.

## Steps to reproduce:
int k = 4;
k = k / 0;

## Expected output:
Machine check: divide by zero

## Actual output:
Floating point exception (core dumped)

**Comment by netizen-a** [comment]
This bug likely occurs with modulo as well.

**Comment by philip-w-howard** [comment]
This issue is fixed in V1.0.2. Both division and modulo by zero will not machine check.
