### ISSUE TITLE
machine_reference 7.38 typo

### ISSUE THREAD

**Issue by netizen-a** [philip-w-howard/stackl#28]
In the machine_reference document at section 7.38 the example specifies the following:
```x86asm
Memory[Memory[SP-1]] = Memory[SP-2]
SP--
IP++
```
This is incorrect, because SP is decremented twice, and should instead read:
```x86asm
Memory[Memory[SP-1]] = Memory[SP-2]
SP -= 2
IP++
```

**Comment by philip-w-howard** [comment]
This issue is resolved in V1.0.2
